In [1]:
import numpy as np 

In [2]:
import numpy as np

vector_zeros = np.zeros(10)
vector_zeros


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [22]:
memory_size = vector_zeros.size * vector_zeros.itemsize
memory_size

80

In [4]:
import numpy as np
doc_np_add = np.add.__doc__

print(doc_np_add)


add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

In [5]:
vector = np.arange(10, 50)
vector

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [6]:
reversed_vector = vector[::-1]
reversed_vector



array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [7]:
matrix_3x3 = np.arange(9).reshape(3, 3)
matrix_3x3


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [8]:
import numpy as np

print("int8:", np.iinfo(np.int8))
print("int32:", np.iinfo(np.int32))
print("int64:", np.iinfo(np.int64))
print("float32:", np.finfo(np.float32))
print("float64:", np.finfo(np.float64))


int8: Machine parameters for int8
---------------------------------------------------------------
min = -128
max = 127
---------------------------------------------------------------

int32: Machine parameters for int32
---------------------------------------------------------------
min = -2147483648
max = 2147483647
---------------------------------------------------------------

int64: Machine parameters for int64
---------------------------------------------------------------
min = -9223372036854775808
max = 9223372036854775807
---------------------------------------------------------------

float32: Machine parameters for float32
---------------------------------------------------------------
precision =   6   resolution = 1.0000000e-06
machep =    -23   eps =        1.1920929e-07
negep =     -24   epsneg =     5.9604645e-08
minexp =   -126   tiny =       1.1754944e-38
maxexp =    128   max =        3.4028235e+38
nexp =        8   min =        -max
smallest_normal = 1.1754944e-38  

In [9]:
tableau = np.array([1, 2, 0, 0, 4, 0])


In [11]:
indices_non_nuls = np.nonzero(tableau)



In [12]:
print(indices_non_nuls)


(array([0, 1, 4], dtype=int64),)


In [23]:
matrix_3x3= np.arange(9).reshape(3, 3)
matrix_3x3

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [29]:
non_zero_indices = np.nonzero([1,2,0,0,4,0])
non_zero_indices

(array([0, 1, 4], dtype=int64),)

In [30]:
identify_matrix= np.eye(3)
identify_matrix


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [16]:

vector = np.linspace(0, 1, 12)[1:-1]


random_vector = np.random.random(10)
random_vector.sort()

vector, random_vector


(array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
        0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091]),
 array([0.17702137, 0.22454237, 0.32520069, 0.46265714, 0.4654119 ,
        0.50570646, 0.51369516, 0.59763654, 0.73613037, 0.83478374]))

In [17]:
import numpy as np


vector = np.linspace(0, 1, 12)[1:-1]

random_vector = np.random.random(10)
random_vector.sort()

vector, random_vector


(array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
        0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091]),
 array([0.08182947, 0.08316285, 0.13121143, 0.34701647, 0.38744769,
        0.44169219, 0.68276665, 0.74391431, 0.91109774, 0.94458039]))